/**
 * TranscribeAI - Share Manager
 * Handles sharing transcription results via link, integrations, and exports
 */

class ShareManager {
    constructor() {
        this.shareUrl = '';
        this.transcriptionData = null;
        this.init();
    }

    /**
     * Initialize share manager
     */
    init() {
        this.loadTranscriptionData();
        this.generateShareUrl();
        this.setupCopyLink();
        this.setupDirectShare();
        this.setupExports();
        this.setupCloseButton();
    }

    /**
     * Load transcription data from URL params or storage
     */
    loadTranscriptionData() {
        // In production, this would load actual transcription data
        // For demo, use sample data
        this.transcriptionData = {
            id: 'a1b2-c3d4-e5f6',
            title: 'Meeting Transcription',
            date: new Date().toISOString(),
            transcript: 'Sample transcription text...',
            summary: 'Sample summary...',
            actionItems: []
        };
    }

    /**
     * Generate shareable URL
     */
    generateShareUrl() {
        const baseUrl = window.location.origin;
        const resultId = this.transcriptionData.id;
        this.shareUrl = `${baseUrl}/results/${resultId}`;
        
        const input = document.getElementById('share-link-input');
        if (input) {
            input.value = this.shareUrl;
        }
    }

    /**
     * Set up copy link functionality
     */
    setupCopyLink() {
        const copyBtn = document.getElementById('copy-link-btn');
        const input = document.getElementById('share-link-input');
        
        if (!copyBtn || !input) return;

        copyBtn.addEventListener('click', async () => {
            try {
                await navigator.clipboard.writeText(this.shareUrl);
                this.showCopySuccess(copyBtn);
            } catch (err) {
                // Fallback for older browsers
                input.select();
                document.execCommand('copy');
                this.showCopySuccess(copyBtn);
            }
        });

        // Also allow clicking the input to copy
        input.addEventListener('click', () => {
            input.select();
        });
    }

    /**
     * Show copy success feedback
     */
    showCopySuccess(button) {
        const originalHTML = button.innerHTML;
        
        button.innerHTML = `
            <span class="material-symbols-outlined text-base">check</span>
            <span class="truncate">Copied!</span>
        `;
        button.classList.add('bg-green-500');
        button.classList.remove('bg-primary');

        setTimeout(() => {
            button.innerHTML = originalHTML;
            button.classList.remove('bg-green-500');
            button.classList.add('bg-primary');
        }, 2000);
    }

    /**
     * Set up direct sharing buttons
     */
    setupDirectShare() {
        const notionBtn = document.getElementById('share-notion-btn');
        const slackBtn = document.getElementById('share-slack-btn');
        const emailBtn = document.getElementById('share-email-btn');

        if (notionBtn) {
            notionBtn.addEventListener('click', () => {
                this.shareToNotion();
            });
        }

        if (slackBtn) {
            slackBtn.addEventListener('click', () => {
                this.shareToSlack();
            });
        }

        if (emailBtn) {
            emailBtn.addEventListener('click', () => {
                this.shareToEmail();
            });
        }
    }

    /**
     * Share to Notion
     */
    shareToNotion() {
        console.log('Sharing to Notion...');
        // In production, this would use Notion API
        this.showToast('Opening Notion integration...', 'info');
        
        // Simulate opening Notion
        setTimeout(() => {
            alert('Notion integration would open here. In production, this would use the Notion API to create a new page with your transcription.');
        }, 500);
    }

    /**
     * Share to Slack
     */
    shareToSlack() {
        console.log('Sharing to Slack...');
        // In production, this would use Slack API
        this.showToast('Opening Slack integration...', 'info');
        
        // Simulate Slack webhook
        setTimeout(() => {
            alert('Slack integration would open here. In production, this would use Slack webhooks or API to post the transcription to a channel.');
        }, 500);
    }

    /**
     * Share via Email
     */
    shareToEmail() {
        const subject = encodeURIComponent('Transcription Results - ' + this.transcriptionData.title);
        const body = encodeURIComponent(
            `Check out this transcription:\n\n${this.shareUrl}\n\nGenerated by TranscribeAI`
        );
        
        window.location.href = `mailto:?subject=${subject}&body=${body}`;
    }

    /**
     * Set up export buttons
     */
    setupExports() {
        const pdfBtn = document.getElementById('export-pdf-btn');
        const txtBtn = document.getElementById('export-txt-btn');

        if (pdfBtn) {
            pdfBtn.addEventListener('click', () => {
                this.exportAsPDF();
            });
        }

        if (txtBtn) {
            txtBtn.addEventListener('click', () => {
                this.exportAsTXT();
            });
        }
    }

    /**
     * Export as PDF
     */
    exportAsPDF() {
        console.log('Exporting as PDF...');
        this.showToast('Preparing PDF export...', 'info');
        
        // In production, this would generate actual PDF
        setTimeout(() => {
            this.showToast('PDF export complete!', 'success');
            // Simulate download
            console.log('PDF would be downloaded here');
        }, 1500);
    }

    /**
     * Export as TXT
     */
    exportAsTXT() {
        console.log('Exporting as TXT...');
        
        const content = `
TranscribeAI - Transcription Export
====================================

Title: ${this.transcriptionData.title}
Date: ${new Date(this.transcriptionData.date).toLocaleDateString()}

TRANSCRIPT
----------
${this.transcriptionData.transcript}

SUMMARY
-------
${this.transcriptionData.summary}

Generated by TranscribeAI
        `.trim();

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `transcription-${this.transcriptionData.id}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);

        this.showToast('TXT file downloaded!', 'success');
    }

    /**
     * Set up close button
     */
    setupCloseButton() {
        const closeBtn = document.getElementById('close-share-modal');
        
        if (closeBtn) {
            closeBtn.addEventListener('click', () => {
                this.closeModal();
            });
        }

        // Close on escape key
        document.addEventListener('keydown', (e) => {
            if (e.key === 'Escape') {
                this.closeModal();
            }
        });
    }

    /**
     * Close the modal
     */
    closeModal() {
        // If this is embedded in results page, hide modal
        // Otherwise, redirect back to results
        if (document.referrer.includes('/results')) {
            window.history.back();
        } else {
            window.location.href = '../pages/results.html';
        }
    }

    /**
     * Show toast notification
     */
    showToast(message, type = 'info') {
        const colors = {
            success: 'bg-green-500',
            error: 'bg-red-500',
            info: 'bg-blue-500'
        };

        const icons = {
            success: 'check_circle',
            error: 'error',
            info: 'info'
        };

        const toast = document.createElement('div');
        toast.className = `fixed bottom-4 right-4 ${colors[type]} text-white px-6 py-3 rounded-lg shadow-lg flex items-center gap-2 z-50 animate-slide-up`;
        toast.innerHTML = `
            <span class="material-symbols-outlined">${icons[type]}</span>
            <span>${message}</span>
        `;
        document.body.appendChild(toast);

        setTimeout(() => {
            toast.remove();
        }, 3000);
    }
}

// Add animation styles
const style = document.createElement('style');
style.textContent = `
    @keyframes slide-up {
        from {
            transform: translateY(100%);
            opacity: 0;
        }
        to {
            transform: translateY(0);
            opacity: 1;
        }
    }
    
    .animate-slide-up {
        animation: slide-up 0.3s ease-out;
    }
`;
document.head.appendChild(style);

// Initialize share manager when DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => {
        window.shareManager = new ShareManager();
    });
} else {
    window.shareManager = new ShareManager();
}
